import { z } from "zod";

export const SeveritySchema = z.enum(["CRITICAL", "HIGH", "MEDIUM", "LOW"]);
export const PrecisionSchema = z.enum(["EXACT", "DATE_ONLY", "UNKNOWN"]);
const SourceRefSchema = z.object({ evidenceId: z.string().min(1), page: z.number().int().positive().optional(), paragraph: z.string().min(1).optional(), sha256: z.string().regex(/^[0-9a-f]{64}$/i).optional() }).strict();
const QuoteSchema = z.string().min(15).max(200);
const TransactionSchema = z.object({ date: z.string(), amount: z.number(), currency: z.string().min(1), sender: z.string().min(1), receiver: z.string().min(1), description: z.string(), evidenceQuote: QuoteSchema, sourceEvidenceId: z.string().min(1), sourcePage: z.number().int().positive().optional(), sourceParagraph: z.string().min(1).optional(), sourceSha256: z.string().regex(/^[0-9a-f]{64}$/i).optional() }).strict();
const ActionSchema = z.object({ actionDate: z.string(), registryType: z.enum(["ORSR","RPO","KATASTER","NOTARSKY_CENTRALNY_REGISTER"]), actionType: z.enum(["PREVOD_OBCHODNEHO_PODIELU","VYMAZ_STATUTARA","MENOVANIE_STATUTARA","ZMENA_SIDLA","ZRIADENIE_ZALOZNEHO_PRAVA","PREVOD_NEHNUTELNOSTI","PLOMBA_O_ZMENE_PRAVA"]), affectedEntity: z.string().min(1), actorFrom: z.string().optional(), actorTo: z.string().optional(), evidenceQuote: QuoteSchema, sourceEvidenceId: z.string().min(1), sourcePage: z.number().int().positive().optional(), sourceParagraph: z.string().min(1).optional(), sourceSha256: z.string().regex(/^[0-9a-f]{64}$/i).optional() }).strict();
export const TemporalCorridorSchema = z.object({ corridorId: z.string().min(1), severity: SeveritySchema, precision: PrecisionSchema, primaryTransaction: TransactionSchema, corporateOrCadastralAction: ActionSchema, timeDeltaHours: z.number().nonnegative().nullable(), forensicPattern: z.enum(["EXIT_PRED_RAZIOU_A_VYBEROM","VYPRATANIE_UCTU_A_PREVOD_NA_NOMINANTA","OCHRANA_MAJETKU_ZALOZNYM_PRAVOM","IZOLACIA_SKUTOCNEHO_UZIVATELA_VYHOD","KARUSELOVY_ROZPTYL_DO_ZAHRANICIA"]), forensicDeduction: z.string() }).strict();
export const NomineeRiskEntitySchema = z.object({ fullName: z.string().min(1), role: z.string(), company: z.string(), strawManIndicators: z.array(z.string()), riskScore: z.number().min(0).max(100), sourceEvidenceQuote: QuoteSchema, sourceEvidenceId: z.string().min(1), sourcePage: z.number().int().positive().optional(), sourceParagraph: z.string().min(1).optional(), sourceSha256: z.string().regex(/^[0-9a-f]{64}$/i).optional(), classification: z.enum(["FACT","INDICATOR","HYPOTHESIS","UNVERIFIED"]) }).strict();
export const ForensicAssetReportSchema = z.object({ caseExecutiveSummary: z.string(), temporalCorridors: z.array(TemporalCorridorSchema), nomineeRiskEntities: z.array(NomineeRiskEntitySchema), legalAssessment: z.object({ suggestedQualification: z.string().optional(), subjectiveAspectAssessment: z.string(), objectiveAspectAssessment: z.string(), confidence: z.enum(["LOW","MEDIUM","HIGH"]), status: z.enum(["HYPOTHESIS","SUPPORTED","UNVERIFIED"]), sourceReferences: z.array(SourceRefSchema) }).strict(), proceduralActions: z.array(z.object({ section: z.string(), target: z.string(), justification: z.string(), status: z.enum(["SUGGESTED","REQUIRES_LEGAL_REVIEW","UNVERIFIED"]), sourceReferences: z.array(SourceRefSchema) }).strict()) }).strict();
export type ForensicAssetCorrelationReport = z.infer<typeof ForensicAssetReportSchema>;
