// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request
        ? input.headers
        : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) =>
        headers.set(key, value),
      );
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

const DEV_CLAIMS = {
  sub: "dev-user-id",
  role: "authenticated",
  email: "dev@forendo.local",
} as unknown as import("@supabase/supabase-js").JwtPayload;

let _devSupabaseClient: ReturnType<typeof createClient<Database>> | undefined;

function getDevSupabaseClient(url: string, key: string) {
  if (!_devSupabaseClient) {
    _devSupabaseClient = createClient<Database>(url, key, {
      global: {
        fetch: createSupabaseFetch(key),
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
        detectSessionInUrl: false,
      },
    });
  }
  return _devSupabaseClient;
}

export const requireSupabaseAuth = createMiddleware({
  type: "function",
}).server(async ({ next }) => {
  const isDev = process.env["NODE_ENV"] !== "production";
  const SUPABASE_URL =
    process.env["SUPABASE_URL"] ||
    process.env["NEXT_PUBLIC_SUPABASE_URL"] ||
    (isDev ? "https://placeholder-project.supabase.co" : undefined);
  const SUPABASE_PUBLISHABLE_KEY =
    process.env["SUPABASE_PUBLISHABLE_KEY"] ||
    process.env["NEXT_PUBLIC_SUPABASE_ANON_KEY"] ||
    (isDev ? "placeholder-publishable-key" : undefined);

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  const request = getRequest();

  if (!request?.headers) {
    if (isDev) {
      const supabase = getDevSupabaseClient(
        SUPABASE_URL!,
        SUPABASE_PUBLISHABLE_KEY!,
      );
      return next({
        context: {
          supabase,
          userId: "dev-user-id",
          claims: DEV_CLAIMS,
        },
      });
    }
    throw new Error("Unauthorized: No request headers available");
  }

  const authHeader = request.headers.get("authorization");

  // Lokálny vývojársky bypass — nikdy nie v produkcii a len ak chýba token.
  if (isDev && !authHeader) {
    const supabase = getDevSupabaseClient(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
    );
    return next({
      context: {
        supabase,
        userId: "dev-user-id",
        claims: DEV_CLAIMS,
      },
    });
  }

  if (!authHeader) {
    throw new Error("Unauthorized: No authorization header provided");
  }

  if (!authHeader.startsWith("Bearer ")) {
    throw new Error("Unauthorized: Only Bearer tokens are supported");
  }

  const token = authHeader.replace("Bearer ", "");
  if (!token) {
    throw new Error("Unauthorized: No token provided");
  }

  if (token.split(".").length !== 3) {
    if (isDev) {
      const supabase = getDevSupabaseClient(
        SUPABASE_URL!,
        SUPABASE_PUBLISHABLE_KEY!,
      );
      return next({
        context: {
          supabase,
          userId: "dev-user-id",
          claims: DEV_CLAIMS,
        },
      });
    }
    throw new Error("Unauthorized: Invalid token");
  }

  const supabase = createClient<Database>(
    SUPABASE_URL!,
    SUPABASE_PUBLISHABLE_KEY!,
    {
      global: {
        fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    },
  );

  const { data, error } = await supabase.auth.getClaims(token);
  if (error || !data?.claims) {
    throw new Error("Unauthorized: Invalid token");
  }

  if (!data.claims.sub) {
    throw new Error("Unauthorized: No user ID found in token");
  }

  return next({
    context: {
      supabase,
      userId: data.claims.sub,
      claims: data.claims,
    },
  });
});
