// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request
        ? input.headers
        : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) =>
        headers.set(key, value),
      );
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  const isDev =
    typeof process !== "undefined"
      ? process.env?.["NODE_ENV"] !== "production"
      : true;

  const viteEnv =
    typeof import.meta !== "undefined"
      ? (import.meta as Record<string, any>)["env"]
      : undefined;

  const SUPABASE_URL =
    (typeof process !== "undefined" &&
      (process.env?.["NEXT_PUBLIC_SUPABASE_URL"] ||
        process.env?.["SUPABASE_URL"])) ||
    viteEnv?.["VITE_SUPABASE_URL"] ||
    (isDev ? "https://placeholder-project.supabase.co" : undefined);

  const SUPABASE_PUBLISHABLE_KEY =
    (typeof process !== "undefined" &&
      (process.env?.["NEXT_PUBLIC_SUPABASE_ANON_KEY"] ||
        process.env?.["SUPABASE_PUBLISHABLE_KEY"])) ||
    viteEnv?.["VITE_SUPABASE_PUBLISHABLE_KEY"] ||
    (isDev ? "placeholder-publishable-key" : undefined);

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.warn(`[Supabase] ${message}`);
    return null as any;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined | null;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy(
  {} as ReturnType<typeof createSupabaseClient>,
  {
    get(_, prop, receiver) {
      if (_supabase === undefined) _supabase = createSupabaseClient();
      if (!_supabase) return undefined;
      return Reflect.get(_supabase, prop, receiver);
    },
  },
);
