import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { assertAiConsent } from "@/lib/ai-consent";
import { parseAiJson } from "./ai/parse-json";
import { ForensicAssetReportSchema } from "./ai/asset-timeline-schema";
import { ASSET_TIMELINE_PROMPT_SHA256, ASSET_TIMELINE_PROMPT_VERSION, ASSET_TIMELINE_SYSTEM_PROMPT } from "./ai/asset-timeline-prompt";
import { enforceDeterminism, validateReportSources } from "./ai/asset-timeline-engine";
import { canonicalJson, canonicalSha256 } from "./provenance/canonical";

const inputSchema = z.object({ caseId: z.string().uuid(), evidenceIds: z.array(z.string().uuid()).min(1).max(10), consentVersion: z.string().min(1), idempotencyKey: z.string().max(200).optional() }).strict();
export const runAssetTimelineForensics = createServerFn({ method: "POST", id: "ai/runAssetTimelineForensics" }).middleware([requireSupabaseAuth]).validator((d: unknown) => inputSchema.parse(d)).handler(async ({ data, context }) => {
  assertAiConsent(data.consentVersion);
  const supabase = context.supabase as any;
  const { data: ownedCase, error: caseError } = await supabase.from("cases").select("id").eq("id", data.caseId).maybeSingle();
  if (caseError || !ownedCase) throw new Error("Prípad sa nenašiel alebo naň nemáte oprávnenie.");
  const { loadLedgerDocuments, ledgerDocumentsText } = await import("./evidence-source");
  const { escapeLike } = await import("@/lib/storage/evidence-ledger");
  const { downloadCaseDocument } = await import("@/lib/storage/s3-vault");
  const { extractSingleBufferText } = await import("./ai/document-parser");
  const loaded = await loadLedgerDocuments(data.caseId, data.evidenceIds, { fetchRows: async ids => { const q = await supabase.from("evidence_items").select("id,file_name,file_size,sha256_hash,s3_object_key,hash_verification_status").in("id", ids).like("s3_object_key", `cases/${escapeLike(data.caseId)}/evidence/%`); if (q.error) throw new Error("Ledger dôkazov sa nepodarilo načítať."); return q.data ?? []; }, download: async key => (await downloadCaseDocument(key))?.buffer ?? null, extract: async (name, buffer) => (await extractSingleBufferText(name, buffer.toString("base64"))).text });
  if (loaded.rejected.length || !loaded.documents.length) throw new Error(`Dôkazy neprešli overením: ${loaded.rejected.map(r => r.evidenceId).join(",")}`);
  const sources = new Map(loaded.documents.map(d => [d.evidenceId, d.text]));
  const evidenceBindings = loaded.documents.map(d => ({ evidenceId: d.evidenceId, fileName: d.fileName }));
  const input = { caseId: data.caseId, evidenceBindings, text: ledgerDocumentsText(loaded.documents), promptVersion: ASSET_TIMELINE_PROMPT_VERSION };
  const inputSha256 = canonicalSha256(input);
  const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
  const db = supabaseAdmin as any;
  const idempotencyKey = data.idempotencyKey ?? canonicalSha256({ type: "ASSET_TIMELINE_FORENSICS", caseId: data.caseId, evidenceBindings, promptVersion: ASSET_TIMELINE_PROMPT_VERSION });
  const existing = await db.from("forensic_asset_timeline_runs").select("*").eq("case_id", data.caseId).eq("idempotency_key", idempotencyKey).maybeSingle();
  if (existing.data) return { success: true, report: existing.data.result, run: existing.data };
  const metadata = await db.from("forensic_workflow_runs").insert({ case_id: data.caseId, user_id: context.userId, workflow_type: "ASSET_TIMELINE_FORENSICS", idempotency_key: idempotencyKey, status: "queued" }).select("id").single();
  if (metadata.error) throw new Error(metadata.error.message);
  const { callLlm, activeProvider, preferredLlmModel } = await import("./ai/llm.server");
  const provider = activeProvider("analysis");
  if (!provider) throw new Error("AI poskytovateľ nie je nakonfigurovaný.");
  const model = preferredLlmModel(provider);
  const llm = await callLlm({ purpose: "analysis", messages: [{ role: "system", content: ASSET_TIMELINE_SYSTEM_PROMPT }, { role: "user", content: `${canonicalJson(input)}\nVráť iba JSON podľa schémy.` }] });
  if (llm.status !== "ok") throw new Error(llm.message);
  const parsed = parseAiJson(llm.content, ForensicAssetReportSchema);
  if (!parsed.ok) throw new Error(parsed.error);
  const report = enforceDeterminism(validateReportSources(parsed.data, sources), sources);
  const resultSha256 = canonicalSha256(report);
  const inserted = await db.from("forensic_asset_timeline_runs").insert({ case_id: data.caseId, user_id: context.userId, workflow_metadata_id: metadata.data.id, status: "COMPLETED", idempotency_key: idempotencyKey, input_sha256: inputSha256, prompt_version: ASSET_TIMELINE_PROMPT_VERSION, prompt_sha256: ASSET_TIMELINE_PROMPT_SHA256, provider: llm.provider ?? provider, model, evidence_bindings: evidenceBindings, result: report, result_sha256: resultSha256 }).select("*").single();
  if (inserted.error) throw new Error(inserted.error.message);
  await db.from("forensic_workflow_runs").update({ status: "completed", completed_at: new Date().toISOString() }).eq("id", metadata.data.id);
  return { success: true, report, run: inserted.data };
});
